// SynthCard - the live legend.
//
// Hold a modifier and the body of the screen becomes a list of everything that
// modifier binds, right now. Release and it is gone; a quick chord - the way
// the keys are actually played - never shows it at all.
//
// The list is GENERATED by walking every key through mapAction(), which is the
// same function the input handler uses. A binding therefore cannot exist
// without appearing here, and an entry here cannot describe a key that is not
// bound. That property is the entire point: the previous manual was written by
// hand, and hand-written descriptions drift - drums.cpp promised six
// oscillators and summed two for who knows how long.
#include "../app.h"
#include "ui.h"

namespace synth {

using namespace ui;

namespace {

struct Entry {
    char keys[12];
    const char* label;
};

// Adjacent keys that map to the same action with stepping arguments - the
// eight step keys, the mode jumps - collapse into one row, so the legend reads
// "1-8  STEP" rather than eight nearly identical lines.
int collectEntries(const Mods& m, Entry* out, int maxOut) {
    int n = 0;
    for (uint8_t id = 0; id < kKeyCount && n < maxOut; ) {
        if (isModifierKey(id)) { ++id; continue; }
        const Action a = mapAction(id, m);
        if (a.act == A_NONE || actionLabel(a.act)[0] == 0) { ++id; continue; }

        uint8_t last = id;
        for (uint8_t j = (uint8_t)(id + 1); j < kKeyCount; ++j) {
            // Keys only merge if they are physically adjacent on the same row.
            if (j / 14 != id / 14) break;
            const Action b = mapAction(j, m);
            if (b.act != a.act) break;
            last = j;
        }
        if (last > id + 1) snprintf(out[n].keys, sizeof(out[n].keys), "%s-%s",
                                    keyName(id), keyName(last));
        else               snprintf(out[n].keys, sizeof(out[n].keys), "%s", keyName(id));
        out[n].label = actionLabel(a.act);
        ++n;
        id = (uint8_t)(last + 1);
    }
    return n;
}

const char* modName(const Mods& m) {
    if (m.fn)    return "FN";
    if (m.shift) return "SHIFT";
    if (m.ctrl)  return "CTRL";
    if (m.alt)   return "ALT";
    return "";
}

}  // namespace

bool legendActive(const App& a, uint32_t now) {
    const Mods& m = a.keys.mods();
    if (!(m.fn || m.shift || m.ctrl || m.alt)) return false;
    return (uint32_t)(now - a.modsSince) >= kLegendHoldMs;
}

void uiDrawLegend(App& a) {
    M5Canvas& g = uiCanvas();
    Entry e[24];
    const Mods& m = a.keys.mods();
    const int n = collectEntries(m, e, 24);

    const int x0 = 0, y0 = BODY_Y, w = W, h = BODY_H;
    g.fillRect(x0, y0, w, h, C_BG);
    panel(g, x0 + 1, y0, w - 2, h, C_PANEL, C_ACCENT);

    char head[40];
    snprintf(head, sizeof(head), "HOLD %s", modName(m));
    textAt(g, x0 + 5, y0 + 2, head, C_ACCENT, &fonts::Font0);
    textAt(g, x0 + w - 5, y0 + 2, "release to play", C_FAINT, &fonts::Font0,
           textdatum_t::top_right);
    g.drawFastHLine(x0 + 4, y0 + 12, w - 8, C_GRID);

    if (n == 0) {
        textAt(g, x0 + w / 2, y0 + h / 2 - 4, "nothing bound", C_DIM, &fonts::Font0,
               textdatum_t::top_center);
        return;
    }

    // Three columns of seven. Entries stay in physical key order down each
    // column, so scanning the legend mirrors scanning the keyboard.
    const int cols = 3, rows = 7;
    const int colW = (w - 10) / cols, rowH = 12;
    for (int i = 0; i < n && i < cols * rows; ++i) {
        const int c = i / rows, r = i % rows;
        const int x = x0 + 5 + c * colW, y = y0 + 15 + r * rowH;
        textAt(g, x, y, e[i].keys, C_ACC2, &fonts::Font0);
        textAt(g, x + 26, y, e[i].label, C_TEXT, &fonts::Font0);
    }
    if (n > cols * rows) {
        char more[24];
        snprintf(more, sizeof(more), "+%d more", n - cols * rows);
        textAt(g, x0 + w - 5, y0 + h - 10, more, C_FAINT, &fonts::Font0,
               textdatum_t::top_right);
    }
}

}  // namespace synth
