// Generates CONTROLS.md from the binding tables.
//
// The old manual was written by hand, and hand-written descriptions drift away
// from the code they describe - drums.cpp promised six oscillators and summed
// two. Every key table below is produced by walking mapAction(), the same
// function the firmware dispatches through, so the document cannot describe a
// binding that does not exist or miss one that does.
//
// The prose lives here too, so there is exactly one source for both.
#include "input/keys.h"
#include "audio/drums.h"
#include "audio/patch.h"
#include "sequencer/sequencer.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace synth;

namespace {

struct Row { std::string keys, action; };

// Adjacent keys on the same row that share an action collapse into one entry,
// so eight step keys read as "1-8" rather than eight lines.
std::vector<Row> layer(const Mods& m) {
    std::vector<Row> rows;
    for (uint8_t id = 0; id < kKeyCount; ) {
        if (isModifierKey(id)) { ++id; continue; }
        const Action a = mapAction(id, m);
        if (a.act == A_NONE) { ++id; continue; }
        uint8_t last = id;
        for (uint8_t j = (uint8_t)(id + 1); j < kKeyCount; ++j) {
            if (j / 14 != id / 14) break;
            if (mapAction(j, m).act != a.act) break;
            last = j;
        }
        Row r;
        r.keys = (last > id + 1) ? (std::string(keyName(id)) + "-" + keyName(last))
                                 : std::string(keyName(id));
        r.action = actionLabel(a.act);
        rows.push_back(r);
        id = (uint8_t)(last + 1);
    }
    return rows;
}

void emitLayer(FILE* f, const char* title, const char* prefix, const Mods& m) {
    fprintf(f, "\n### %s\n\n| Key | Action |\n| --- | --- |\n", title);
    for (const Row& r : layer(m)) {
        // Backticks around the key, so a lone backtick key does not break the
        // table.
        if (r.keys == "`") fprintf(f, "| %s`` ` `` | %s |\n", prefix, r.action.c_str());
        else               fprintf(f, "| %s`%s` | %s |\n", prefix, r.keys.c_str(), r.action.c_str());
    }
}

}  // namespace

int main() {
    FILE* f = fopen("../CONTROLS.md", "w");
    if (!f) { fprintf(stderr, "cannot write ../CONTROLS.md\n"); return 1; }

    fprintf(f,
"# SynthCard - Controls\n"
"\n"
"<!-- GENERATED by test/gen_controls.cpp from the binding tables. Do not edit\n"
"     by hand: run `make -C test controls-md` instead. The key tables below are\n"
"     produced by walking mapAction(), the same function the firmware\n"
"     dispatches through, so they cannot go stale. -->\n"
"\n"
"Everything is one keypress deep. Without a modifier the bottom two rows are\n"
"always a musical keyboard.\n"
"\n"
"**You do not have to memorise any of this.** Hold `FN`, `SHIFT` or `CTRL` for a\n"
"moment and the screen lists everything that modifier does, right now, on the\n"
"screen you are on. Let go and you are playing again. Press `` ` `` for the\n"
"manual of the current tab.\n"
"\n"
"## Musical keyboard\n"
"\n"
"Rows 3 and 4 are a piano, laid out the way trackers have done it for decades.\n"
"`-` / `=` move the octave.\n"
"\n"
"```\n"
"  black:      S  D     G  H  J     L  ;\n"
"  white:    Z  X  C  V  B  N  M  ,  .  /\n"
"  note:     C  D  E  F  G  A  B  C' D' E'\n"
"```\n"
"\n"
"Seventeen semitones, C through E an octave up. Hold `SHIFT` while playing for\n"
"an accent (velocity 127), `ALT` for a soft note (62); otherwise 100.\n"
"\n");

    // The drum pads, straight from keyToDrumLane so the list cannot disagree
    // with what the keys actually do.
    fprintf(f, "On the **DRUM** page those same keys become the %d drum pads:\n\n```\n", DL_COUNT);
    for (uint8_t id = 0; id < kKeyCount; ++id) {
        const int8_t lane = keyToDrumLane(id);
        if (lane < 0 || lane >= DL_COUNT) continue;
        fprintf(f, "  %-5s %s\n", keyName(id), kDrumNames[lane]);
    }
    fprintf(f, "```\n");

    Mods none, fn, shift, ctrl;
    fn.fn = true; shift.shift = true; ctrl.ctrl = true;

    fprintf(f, "\n## Every key, by layer\n");
    emitLayer(f, "No modifier", "", none);
    emitLayer(f, "FN - the command layer", "`FN`+", fn);
    emitLayer(f, "SHIFT - the pattern layer", "`SHIFT`+", shift);
    emitLayer(f, "CTRL", "`CTRL`+", ctrl);

    fprintf(f,
"\n## Recording\n"
"\n"
"1. `\\` arms the recorder and starts the transport. The top bar turns red.\n"
"2. Play. Notes land on the nearest step of the pattern that is running and\n"
"   loop straight back at you.\n"
"3. **Held length is recorded.** Hold a key for two steps and it plays back two\n"
"   steps long, not as a stub.\n"
"4. Wrong note? **Hold `BKSP`** while it loops past and it is rubbed out.\n"
"5. `\\` again disarms. Everything you recorded is normal pattern data.\n"
"\n"
"`FN`+`BKSP` clears the whole track, and `CTRL`+`Z` undoes the whole take -\n"
"arming the recorder takes a snapshot first. Pressing `CTRL`+`Z` again redoes it.\n"
"\n"
"## The screens\n"
"\n"
"**PLAY** - `[`/`]` is cutoff, `O`/`P` is resonance, `FN`+`;`/`.` switches\n"
"between the LEAD and BASS track. The scope shows the master output.\n"
"\n"
"**DRUM** - `FN`+`;`/`.` picks the lane; the list scrolls, since there are\n"
"twelve. `O`/`P` walks PUNCH / TONE / SPACE and then the eight detail knobs\n"
"(tune, decay, tone, level, snap, drive, delay, reverb), and `[`/`]` adjusts,\n"
"auditioning as you go. The closed hat, open hat and ride cut each other off,\n"
"marked with a dot in the lane list.\n"
"\n"
"**SEQ** - `FN`+`;`/`.` picks the track. Playing a note key writes it into the\n"
"selected step and advances. `O`/`P` picks the field, `[`/`]` edits.\n"
"\n"
"**SOUND** - the parameter pages for the current engine. `O`/`P` walks every\n"
"parameter and **wraps across page boundaries**, so the page keys are a\n"
"shortcut rather than something you need. Changing ENGINE reloads that engine's\n"
"own controls and leaves your filter, envelopes and levels alone.\n"
"\n"
"**FX** - the master bus: delay (free or synced to the tempo), plate reverb,\n"
"chorus, tilt, compressor, drive and master level.\n"
"\n"
"**SONG** - `FN`+`;`/`.` moves through the arrangement, `O`/`P` picks the\n"
"pattern or repeat field, `[`/`]` edits, `ENTER` appends a slot, `BKSP` removes\n"
"one.\n"
"\n"
"**SETUP** - two tabs, FILES and SYSTEM; `FN`+`7` switches between them.\n"
"FILES saves and loads to `SD:/synthcard/NAME.SCP` and writes nothing to the\n"
"card until you ask it to. SYSTEM holds volume, brightness, output mode,\n"
"metronome, swing, scale, root, chord mode, the arpeggiator and pattern length,\n"
"with a live column showing CPU, voices, free RAM, frame rate and battery.\n"
"\n"
"**OUTPUT** is worth knowing about. On `SPEAKER` the master is high-passed at\n"
"120 Hz, because the Cardputer's speaker cannot reproduce anything below about\n"
"200 Hz and that energy otherwise drives the limiter - a big kick ducking the\n"
"whole mix in exchange for something nobody can hear. Switch to `LINE` for\n"
"headphones.\n");

    // The engines and their parameter pages, from the tables themselves.
    fprintf(f, "\n## Engines\n\nEach engine brings its own parameter pages:\n\n");
    for (uint8_t e = 0; e < ENG_COUNT; ++e) {
        fprintf(f, "- **%s** - ", kEngineNames[e]);
        const ParamPage* pages = synthPages(e);
        for (uint8_t p = 0; p < synthPageCount(e); ++p)
            fprintf(f, "%s%s", p ? ", " : "", pages[p].name);
        fprintf(f, "\n");
    }

    fprintf(f, "\n## Drum kits\n\n");
    for (uint8_t k = 0; k < kKitCount; ++k)
        fprintf(f, "%s`%s`", k ? ", " : "", kKits[k].name);
    fprintf(f, "\n\n## Sounds\n\n%d presets across the six engines.\n", (int)kPresetCount);

    fclose(f);
    printf("wrote CONTROLS.md\n");
    return 0;
}
