// SynthCard - band-limited wavetables. GENERATED by tools/gen_wavetables.py.
// Do not edit by hand; edit the generator and re-run it.
//
// Six mip levels per table, additively synthesised with the harmonic sum
// truncated at each level's Nyquist, so every level is alias-free by
// construction. const data, so this lives in flash and costs no RAM.
#pragma once
#include <stdint.h>

namespace synth {

constexpr int kWtTables = 16;
constexpr int kWtLevels = 6;
constexpr int kWtSize[kWtLevels] = {256, 128, 64, 32, 16, 8};
// Offset of each level inside a table's flat sample block.
constexpr int kWtOffset[kWtLevels] = {0, 256, 384, 448, 480, 496};
constexpr int kWtStride = 504;

extern const int16_t kWaveTables[kWtTables][kWtStride];

}  // namespace synth
