#!/usr/bin/env python3
"""Generates SynthCard/src/audio/wavetables.h.

Every table is defined as a harmonic amplitude/phase spectrum and rendered by
additive synthesis. Band-limiting per mip level is then just truncating the
harmonic sum, so each level is alias-free by construction rather than by
filtering after the fact.

Six mip levels (256..8 samples, 128..4 harmonics) let a table stay clean from
the bottom of the keyboard to the top:

    level 0  256 samples  128 harmonics  up to  125 Hz
    level 1  128           64                   250 Hz
    level 2   64           32                   500 Hz
    level 3   32           16                  1000 Hz
    level 4   16            8                  2000 Hz
    level 5    8            4                  4000 Hz

Stdlib only - no numpy.
"""
import math
import os
import random

LEVELS = [256, 128, 64, 32, 16, 8]
MAXH = 128


def saw():
    return {n: (1.0 / n, 0.0) for n in range(1, MAXH + 1)}


def square():
    return {n: (1.0 / n, 0.0) for n in range(1, MAXH + 1, 2)}


def triangle():
    out = {}
    for i, n in enumerate(range(1, MAXH + 1, 2)):
        out[n] = (1.0 / (n * n), 0.0 if i % 2 == 0 else 0.5)
    return out


def sine():
    return {1: (1.0, 0.0)}


def pulse(width):
    # Fourier series of a rectangular pulse of the given duty cycle.
    out = {}
    for n in range(1, MAXH + 1):
        a = math.sin(math.pi * n * width) / (math.pi * n)
        if abs(a) > 1e-6:
            out[n] = (a, 0.25)
    return out


def formant(peaks, tilt=1.0):
    """Harmonics shaped by gaussian formant peaks at the given harmonic numbers."""
    out = {}
    for n in range(1, MAXH + 1):
        a = 0.0
        for centre, width, gain in peaks:
            a += gain * math.exp(-((n - centre) ** 2) / (2.0 * width * width))
        a += 0.05 / (n ** tilt)
        if a > 1e-4:
            out[n] = (a, 0.0)
    return out


def partials(spec):
    return {n: (a, ph) for n, a, ph in spec}


def gritty(seed):
    rnd = random.Random(seed)
    out = {}
    for n in range(1, 49):
        out[n] = (rnd.uniform(0.15, 1.0) / (n ** 0.6), rnd.random())
    return out


TABLES = [
    ("SAW", saw()),
    ("SQUARE", square()),
    ("TRI", triangle()),
    ("SINE", sine()),
    ("PULSE25", pulse(0.25)),
    ("PULSE12", pulse(0.125)),
    # Vowel-ish formant stacks: two peaks each, roughly at /a/, /e/, /o/.
    ("VOWEL_A", formant([(7, 2.2, 1.0), (13, 3.0, 0.7), (2, 1.4, 0.9)])),
    ("VOWEL_E", formant([(4, 1.6, 1.0), (21, 4.0, 0.6), (2, 1.2, 0.8)])),
    ("VOWEL_O", formant([(5, 2.0, 1.0), (8, 2.0, 0.5), (1, 1.0, 1.0)])),
    # Hammond-ish: the drawbar footages as a fixed registration.
    ("ORGAN", partials([(1, 1.0, 0.0), (2, 0.8, 0.0), (3, 0.5, 0.0),
                        (4, 0.6, 0.0), (6, 0.3, 0.0), (8, 0.35, 0.0)])),
    ("BELL", partials([(1, 1.0, 0.0), (2, 0.5, 0.12), (4, 0.45, 0.3),
                       (7, 0.3, 0.55), (11, 0.22, 0.7), (17, 0.12, 0.15)])),
    ("REED", partials([(1, 1.0, 0.0), (2, 0.15, 0.0), (3, 0.7, 0.0),
                       (4, 0.1, 0.0), (5, 0.5, 0.0), (7, 0.35, 0.0),
                       (9, 0.25, 0.0), (11, 0.18, 0.0)])),
    # Wavefolded sine approximations: strong odd harmonics with rotating phase.
    ("FOLD1", partials([(n, 1.0 / (n ** 0.5) * (0.6 if n % 2 == 0 else 1.0), (n * 0.11) % 1.0)
                        for n in range(1, 25)])),
    ("FOLD2", partials([(n, 1.0 / (n ** 0.8), (n * n * 0.037) % 1.0)
                        for n in range(1, 33)])),
    ("GLASS", partials([(n, 1.0 / (n ** 0.35), 0.0) for n in range(8, 41, 4)])),
    ("GRIT", gritty(0xC0FFEE)),
]

assert len(TABLES) == 16, "kTableNames in patch.cpp expects exactly 16 tables"


def render(spec, size):
    limit = size // 2               # harmonics that fit below this level's Nyquist
    out = []
    for i in range(size):
        t = i / size
        s = 0.0
        for n, (amp, ph) in spec.items():
            if n <= limit:
                s += amp * math.sin(2.0 * math.pi * (n * t + ph))
        out.append(s)
    peak = max(abs(v) for v in out) or 1.0
    # 0.985 keeps the int16 round-trip clear of full scale.
    return [int(round(v / peak * 32767 * 0.985)) for v in out]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    dst = os.path.join(here, "..", "SynthCard", "src", "audio", "wavetables.h")
    lines = [
        "// SynthCard - band-limited wavetables. GENERATED by tools/gen_wavetables.py.",
        "// Do not edit by hand; edit the generator and re-run it.",
        "//",
        "// Six mip levels per table, additively synthesised with the harmonic sum",
        "// truncated at each level's Nyquist, so every level is alias-free by",
        "// construction. const data, so this lives in flash and costs no RAM.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace synth {",
        "",
        f"constexpr int kWtTables = {len(TABLES)};",
        f"constexpr int kWtLevels = {len(LEVELS)};",
        "constexpr int kWtSize[kWtLevels] = {" + ", ".join(str(s) for s in LEVELS) + "};",
        "// Offset of each level inside a table's flat sample block.",
    ]
    offs, acc = [], 0
    for s in LEVELS:
        offs.append(acc)
        acc += s
    lines.append("constexpr int kWtOffset[kWtLevels] = {" + ", ".join(str(o) for o in offs) + "};")
    lines.append(f"constexpr int kWtStride = {acc};")
    lines.append("")
    lines.append("extern const int16_t kWaveTables[kWtTables][kWtStride];")
    lines.append("")
    lines.append("}  // namespace synth")
    with open(dst, "w") as f:
        f.write("\n".join(lines) + "\n")

    src = os.path.join(here, "..", "SynthCard", "src", "audio", "wavetables.cpp")
    body = [
        "// GENERATED by tools/gen_wavetables.py - do not edit by hand.",
        '#include "wavetables.h"',
        "",
        "namespace synth {",
        "",
        "const int16_t kWaveTables[kWtTables][kWtStride] = {",
    ]
    for name, spec in TABLES:
        body.append(f"  {{  // {name}")
        for size in LEVELS:
            samples = render(spec, size)
            body.append(f"    // level {LEVELS.index(size)}: {size} samples")
            for i in range(0, len(samples), 12):
                body.append("    " + ", ".join(f"{v:6d}" for v in samples[i:i + 12]) + ",")
        body.append("  },")
    body.append("};")
    body.append("")
    body.append("}  // namespace synth")
    with open(src, "w") as f:
        f.write("\n".join(body) + "\n")
    total = len(TABLES) * acc * 2
    print(f"wrote {dst}")
    print(f"wrote {src}")
    print(f"{len(TABLES)} tables x {acc} samples x 2 bytes = {total} bytes of flash")


if __name__ == "__main__":
    main()
